name: Build to branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/pittst3r/distillate.git

      - name: Publish
        env:
          DEST_BRANCH: rendered
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout --detach
          git fetch origin $DEST_BRANCH
          git branch --track --force $DEST_BRANCH origin/$DEST_BRANCH
          git checkout $DEST_BRANCH -- .
          git commit -am "Base state"
          distillate build .
          git add --all
          git stash
          git checkout $DEST_BRANCH
          git stash pop
          git add --all
          git commit --message="Publish ${{ github.sha }}"
          git push
